name: Go Releaser

on:
    push:
        branches: [main]
        tags:
            - "*"

permissions:
    contents: write

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - uses: goreleaser/goreleaser-action@v6
              with:
                  args: release --clean
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
